version: '3.8'

services:
  postgres:
    container_name: user-management
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management_db
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
